"""phase 4: ingestion pipeline fields + embedding cache

Revision ID: 724d2f11c180
Revises: fe53c9400ef8
Create Date: 2026-07-20 16:19:47.164910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '724d2f11c180'
down_revision: Union[str, Sequence[str], None] = 'fe53c9400ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_cache',
    sa.Column('content_sha', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('content_sha')
    )
    op.add_column('chunks', sa.Column('page', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('content_sha', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_chunks_content_sha'), 'chunks', ['content_sha'], unique=False)
    op.add_column('documents', sa.Column('source_url', sa.String(length=2000), nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('chunks_done', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'chunks_done')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'source_url')
    op.drop_index(op.f('ix_chunks_content_sha'), table_name='chunks')
    op.drop_column('chunks', 'content_sha')
    op.drop_column('chunks', 'page')
    op.drop_table('embedding_cache')
    # ### end Alembic commands ###
