"""phase 6: message trace

Revision ID: 918f6ff3f37c
Revises: ed9510172467
Create Date: 2026-07-20 19:30:38.022572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918f6ff3f37c'
down_revision: Union[str, Sequence[str], None] = 'ed9510172467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('trace', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'trace')
    # ### end Alembic commands ###
