"""phase 5: message seq ordering

Revision ID: ed9510172467
Revises: aa924bbbeaaf
Create Date: 2026-07-20 17:19:24.612502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9510172467'
down_revision: Union[str, Sequence[str], None] = 'aa924bbbeaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('seq', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_seq'), 'messages', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_seq'), table_name='messages')
    op.drop_column('messages', 'seq')
    # ### end Alembic commands ###
