"""Step 3 · EXPORT — write the Ollama Modelfile.

Generated rather than hand-written for the same reason generate_data.py
imports the prompt: `chat.SYSTEM_PROMPT` is the single source of truth, and a
stale copy pasted into a Modelfile would be invisible until the model started
behaving oddly for no traceable reason.

    python training/make_modelfile.py
    cd training && ollama create brainstack-3b -f Modelfile

Note the backend does NOT rely on the SYSTEM block below — services/grounded.py
sends the system prompt with every request. This copy is what makes a bare
`ollama run brainstack-3b` behave the same way, so manual testing matches what
the app does.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.services.chat import SYSTEM_PROMPT  # noqa: E402

# Qwen 2.5 speaks ChatML. Ollama can usually read the template out of the GGUF
# metadata, but stating it makes the served format provably identical to the
# one the notebook trained on — which is the whole game. If your Ollama version
# rejects this syntax, delete the TEMPLATE block: the built-in Qwen template is
# the same thing.
TEMPLATE = """{{- if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{- range .Messages }}<|im_start|>{{ .Role }}
{{ .Content }}<|im_end|>
{{ end }}<|im_start|>assistant
"""

MODELFILE = '''# BrainStack 3B — grounded answering, fine-tuned from Qwen2.5-3B-Instruct.
# GENERATED by training/make_modelfile.py — do not edit by hand; edit the
# prompt in backend/app/services/chat.py and regenerate.

FROM ./{gguf}

TEMPLATE """{template}"""

PARAMETER stop "<|im_end|>"
PARAMETER stop "<|im_start|>"

# Grounded answering should be boring and repeatable — the same passages must
# give the same answer. Matches grounded.TEMPERATURE in the backend.
PARAMETER temperature 0.2
PARAMETER top_p 0.9

# Our prompts run ~500-900 tokens (6 passages + system + answer). 4096 leaves
# room for follow-up turns without spending RAM we do not have.
PARAMETER num_ctx 4096

SYSTEM """{system}"""
'''


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--gguf",
        default="brainstack-3b-q4_k_m.gguf",
        help="the .gguf filename, sitting next to the Modelfile",
    )
    ap.add_argument("--out", default=str(HERE / "Modelfile"))
    args = ap.parse_args()

    out = Path(args.out)
    out.write_text(
        MODELFILE.format(
            gguf=args.gguf, template=TEMPLATE, system=SYSTEM_PROMPT.strip()
        ),
        encoding="utf-8",
    )
    print(f"wrote {out}")

    if not (out.parent / args.gguf).exists():
        print(f"\n  ⚠ {args.gguf} is not here yet.")
        print("    Download it from Colab (notebook Step 3) and put it in")
        print(f"    {out.parent}")
        print("    Then:  ollama create brainstack-3b -f Modelfile")
    else:
        print("\n  next:  ollama create brainstack-3b -f Modelfile")
        print("         ollama run brainstack-3b")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
